name: Server Deploy
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: prod
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
        with:
          elixir-version: '1.12.2'
          otp-version: '24.0'

      - name: Restore Dependencies Cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile Release
        run: MIX_ENV=prod mix compile
      
      - name: Compile Assets
        run: MIX_ENV=prod mix assets.deploy

      - name: Assets digest
        run: mix phx.digest

      - name: Create key base secret
        run: |
          export SECRET_KEY_BASE="$(mix phx.gen.secret)"
          echo "::set-output name=secret_key_base::$SECRET_KEY_BASE"
        id: generate_secret
      
      - name: Release
        run: mix phx.gen.release

      - name: Finish Release
        run: MIX_ENV=prod mix release demo

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_L2L_CONFERENCE }}
          known_hosts: 'to be defined on next step'

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP_ADD }} >> ~/.ssh/known_hosts

      - name: Deploy Release with RSYNC 
        run: rsync -avz ./_build ${{ secrets.APPLICATION_SERVER_SSH_USER_SDX }}@${{ secrets.SERVER_IP_ADD }}:~

      - name: Start Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADD }}
          username: ${{ secrets.APPLICATION_SERVER_SSH_USER_SDX }}
          key: ${{ secrets.SSH_L2L_CONFERENCE }}
          envs: SECRET_KEY_BASE=${{ steps.generate_secret.outputs.secret_key_base }}
          script_stop: true
          script: sudo -S MIX_ENV=prod APP_NAME=demo PORT=4000 _build/prod/rel/demo/bin/demo start